### ISSUE TITLE
Unneeded Video CSS

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSpam-a-not#3]
Looks like we have an extra file (or content) for OSpam-a-not:
https://github.com/OSTraining/OSpam-a-not/blob/master/src/style.css

Looks like it might be part of the builder, but I'm not sure.

Adding @andergmartins and @billtomczak

**Comment by billtomczak** [comment]
nope - just a reminder of the dangers of copy and paste. It was a leftover from the plugin I copied for the initial project layout
