### ISSUE TITLE
Inconsistency text

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSpam-a-not#4]
After installing the plugin, this text is displayed:
"Thanks for installing Ospamanot!"

Ospamanot > Ospam-a-not

**Comment by andergmartins** [comment]
Ah! That is the installer library. The builder script removes all non-alphanumeric from the package name and the installer is getting that name probably from there. Maybe instead show the element, we should show a "translated" version of the name

**Comment by billtomczak** [comment]
lol - sorry about that!
