### ISSUE TITLE
Conflicts with other plugins

### ISSUE THREAD

**Issue by billtomczak** [OSTraining/OSpam-a-not#5]
If OSpam-a-not is not ordered as the last plugin in the system plugins, forms may get added to the document body after it's done it's work.

This can be immediately fixed by re-ordering in the Plugin Manager.

**Comment by stevejburge** [comment]
Should we note this somewhere and / or do it automatically?

Steve



On Friday, January 23, 2015, Bill Tomczak <notifications@github.com> wrote:

> If OSpam-a-not is not ordered as the last plugin in the system plugins,
> forms may get added to the document body after it's done it's work.
>
> This can be immediately fixed by re-ordering in the Plugin Manager.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OSTraining/OSpam-a-not/issues/5>.
>


-- 

--
Steve Burge
CEO | OSTraining
steve@ostraining.com | +1 678-830-2168 ( extension 701 )

**Comment by billtomczak** [comment]
See the most recent commit. I added a note about this in the plugin description and on initial install, the plugin will make sure it's ordered last.

I'm leaving this issue open because I want to also check its ordering during updates.

Basically - fixed in next release :)

**Comment by stevejburge** [comment]
Cheers!

On Friday, January 23, 2015, Bill Tomczak <notifications@github.com> wrote:

> See the most recent commit. I added a note about this in the plugin
> description and on initial install, the plugin will make sure it's ordered
> last.
>
> I'm leaving this issue open because I want to also check its ordering
> during updates.
>
> Basically - fixed in next release :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OSTraining/OSpam-a-not/issues/5#issuecomment-71263074>
> .
>


-- 

--
Steve Burge
CEO | OSTraining
steve@ostraining.com | +1 678-830-2168 ( extension 701 )
